config/routes.rb
Rails.application.routes.draw do
  post "users/logging", to: "users#login", as: "login_in"
  resources :events, except: [:destroy]
  resources :games, only: [:index, :show]
  resources :users, except: [:destroy]

  delete '/logout', to: 'sessions#destroy', as: "logout"
  root 'users#index'
  post "thereisnocowlevel", to: "events#destroy", as: "delete_event"
  post '/joinconfirms', to: "confirms#create", as: "join_event"
  post '.deleteconfirms', to: "confirms#destroy", as: "leave_event"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/confirm.rb
class Confirm < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :game
  belongs_to :user
  has_many :confirms, :dependent => :destroy
  has_many :users, through: :confirms

  validates :location, presence: true
  validates :date, presence: true
  validates :max_player, presence: true

  def full?
    self.users.count >= self.max_player
  end

  def full_message
    self.full? ? "Full" : "Open"
  end

  def self.index_events
    Event.all.select {|e| !e.full?}.shuffle[0..14].sort_by {|e| e.date}
  end

  def sorted_users
    self.users.sort_by {|u|u.username}
  end

  def self.open_events
    Event.all.select {|e| !e.full?}
  end

  def self.sort_by_date
    Event.all.sort_by {|e|e.date}
  end


end

app/models/game.rb
class Game < ApplicationRecord
  has_many :ownerships
  has_many :users, through: :ownerships
  has_many :events

  def self.sort_by_name
    Game.all.sort_by{ |game| game.name}
  end

  def game_name_platform
    "#{name} [#{platform}]"
  end

  def open_events
    events.all.select {|e| !e.full?}
  end

  def random_three_open_events
    open_events.sample(3).sort
  end

end

app/models/ownership.rb
class Ownership < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ownerships
  has_many :games, through: :ownerships
  has_many :events
  has_many :confirms

  validates :email, :username, uniqueness: true
  validates :email, :username,:profile_img, presence: true
  validates :email, :password, length: { minimum: 5 }
  validates :age, numericality: { greater_than_or_equal_to: 18 }

  def games_by_name
    self.games.sort_by{|g| g.name}
  end

  def self.random_user_id
    User.all.map {|u|u.id}.sample
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :hex_color_sample

  def hex_color_sample
    ["FFCCFF", "FAD1FF", "F6D5FF", "F1DAFF", "ECDFFF", "E8E3FF", "E3E8FF", "DFECFF", "DAF1FF", "D5F6FF", "D1FAFF", "CCFFFF"].sample
    "f8f8ff"
  end

end

app/controllers/confirms_controller.rb
class ConfirmsController < ApplicationController

  def create
    Confirm.create(user_id: session[:user_id], event_id: session[:event_id])
    @event = Event.find(session[:event_id])
    session[:event_id] = nil
    redirect_to @event
  end

  def destroy
    Confirm.find_by(event_id: session[:event_id], user_id: session[:user_id]).destroy
    @event = Event.find(session[:event_id])
    session[:event_id] = nil
    redirect_to @event
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.sort_by_date
    @open_events = Event.open_events
  end

  def show
    @event = Event.find(params[:id])
    @confirms = @event.sorted_users
  end

  def new
    if session[:user_id].nil?
      redirect_to :root
    else
      @event = Event.new
      @games = Game.sort_by_name
    end
  end

  def create
    @event = Event.create(event_params)
    if @event.valid?
      Confirm.create(user_id: session[:user_id], event_id: @event.id)
      redirect_to @event
    else
      @games = Game.sort_by_name
      @errors = @event.errors.full_messages
      render :new
    end
  end

  def destroy
    Event.find(session[:event_id]).destroy
    session[:event_id] = nil
    @user = User.find(session[:user_id])
    @hostings = @user.events
    @game_list = @user.games_by_name
    @events = @user.confirms
    redirect_to @user
  end



  private
  def event_params
    params.require(:event).permit(:user_id, :game_id, :location, :max_player, :date)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.sort_by_name
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @events = Event.index_events
  end

  def login
    @user = User.find_by email: params[:email], password: params[:password]
    if @user.nil?
      @error = "Please check your Email and Password and Try again"
      redirect_to :root
    else
      session[:user_id] = @user.id
      redirect_to @user
    end
  end

  def show
    @user = User.find(params[:id])
    if @user.nil?
      redirect_to :root
    else
      @hostings = @user.events
      @game_list = @user.games_by_name
      @events = @user.confirms
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      flash[:notice] = "You account was sussessfully made."
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:notice] = @user.errors.full_messages
      redirect_to "/users/new"
    end
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == session[:user_id]
      redirect_to :root
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.valid?
      redirect_to @user
    else
      flash[:notice] = @user.errors.full_messages
      redirect_to "/users/#{params[:id]}/edit"
    end
  end



  private
  def user_params
    params.require(:user).permit(:email, :password, :age, :username, :profile_img)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirms_helper.rb
module ConfirmsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/ownerships_helper.rb
module OwnershipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.erb
<h1 align= "center">Upcoming events</h1>
<div class="row " style="column-gap: 30px;">
  <% @events.each do |event| %>
  <div class="col-4" style="margin-bottom: 30px;">
    <div class="card-body shadow-lg rounded" style="background-color: #<%= event.full? ? "A9A9A9" : hex_color_sample  %>;" align= "center">
      <%= link_to image_tag(event.game.logo, class: "img-responsive center-block"), event %><%= "#{event.date} [#{event.full_message}]"%><br>
      <%= "#{event.location}" %><br>
      <%= "#{pluralize((event.max_player - event.confirms.count), "slot")} left" %>
    </div>
  </div>
  <% end %>
</div>

app/views/events/new.erb
<h1 align= "center">Host a new event!</h1>
<ul>
  <% if @errors %>
  <div class="alert alert-warning" role="alert">
    <% @errors.each do |e| %>
        <li><%= e %></li>
    <% end %>
  <% end %>
</div>
</ul>

<%= form_for @event do |f| %>
  <div class="col-4 mx-auto">
    <%= f.label "Game:" %>
    <%= f.text_field :user_id, hidden: true, value: session[:user_id]%>
    <%= f.collection_select :game_id, @games, :id, :game_name_platform %><br><br>
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control" %><br>
    <%= f.label :max_player %>
    <%= f.number_field :max_player , min: 2, max: 64, class: "form-control"%><br>
    <%= f.label "Date"%>
    <%= f.date_field :date, class: "form-control",  min: Date.today%><br>
  </div>
    <%= f.submit "Host the Event!", class: "btn btn-primary btn-block col-2 mx-auto" %>
<% end %>

app/views/events/show.erb
<div class="" align="center">
  <%= link_to image_tag(@event.game.logo, width: "55%", class: "img-responsive center-block"), @event.game %>
</div>
<div class="">

</div>
  <p>Hosted by: <%= link_to @event.user.username, user_path(@event.user) %></p>
  <p>Location: <%= @event.location %></p>
  <p>Event Date: <%= @event.date %></p>
  <p>Max Players for this event: <%= @event.max_player %></p>
  <p>Current Number of Players attending this event: <%= @event.users.count %></p>
</div>


<% if session[:user_id].nil?%>
  <% if @event.full? %>
    This Event is full, Find other events for <%= link_to "#{@event.game.name}", @event.game%>
  <% else %>
    Login to Join this Event
  <% end  %>
<% elsif @event.users.include?(User.find(session[:user_id]))%>
  <% session[:event_id] = @event.id  %>
  <%= button_to "Leave Event", leave_event_path, class: "btn btn-danger col-2"%>
<% elsif @event.full? %>
  This Event is full, Find other events for <%= link_to "#{@event.game.name}", @event.game%>
<% else %>
  <% session[:event_id] = @event.id %>
  <%= button_to "Join Event", join_event_path, class: "btn btn-primary col-2"%>
<% end %>

<h2 align= "center">Attendees</h2>
<div class="row">
    <% @confirms.each do |confirm| %>
  <div class="col-sm-3">
    <div class="card" style="margin-bottom: 30px;">
      <div class="card-body rounded" align= "center">
        <%= link_to image_tag(confirm.profile_img, width: "95%", class: "rounded"), confirm %>
        <%=confirm.username %>
      </div>
    </div>
  </div>
  <% end %>
  </div>


<% unless session[:user_id].nil?%>
  <% if @event.user == User.find(session[:user_id]) %>
    <% session[:event_id] = @event.id %>
    <%= button_to "Delete Event", delete_event_path, class: "btn btn-danger btn-block col-4 mx-auto"%>
  <% end %>
<% end %>

app/views/games/index.erb
<div class="card-columns" style="column-gap: 30px;">
  <% @games.each do |game| %>
    <div class="card shadow-lg rounded" style="margin-bottom: 30px;">
      <%= link_to image_tag(game.logo, class: "img-responsive center-block"), game %>
      <div class="card-body">
        <h5><%= game.platform %></h5>
      <h5 class="card-title"><%= "Active Players: #{game.ownerships.count}" %></h5>
      <span class="card-text">
        <% game.random_three_open_events.each do |event| %>
        [ <%= link_to event.date, event%> ]
      <% end %>
      <% if game.random_three_open_events.count == 0%>
        <%= "There are no upcoming events." %>
      <% end %>
    </span>
    </div>
    <div class="card-footer">
      <large class="text-muted">
        <%= game.open_events.count unless game.open_events.count == 0%>
        <% case game.open_events.count %>
        <% when 1 %>
          <%= "open event" %>
        <% when 0 %>
          <%= link_to "Make a new Event", "events/new", class: "nav-link" %>
        <% else %>
          <%= "open events" %>
        <% end %>
      </large>
    </div>
    </div>
  <% end %>
  </div>

app/views/games/show.erb
<div class="" align="center" >
  <img src="<%= @game.logo %>" alt="<%= @game.name %>" width = "55%" >
  <br><br>
  <p><%= @game.description %></p>
  <p>Max Players Per Session: <%= @game.max_players %></p>
  <p>Platform: <%= @game.platform %></p>
  <p>Active Players: <%= @game.users.count %></p>
</div>
<h3 align= "center">Events</h3>
<div class="row">
    <% @game.events.sort_by{|e|e.date}.each do |event| %>
  <div class="col-sm-3">
    <div class="card" style="margin-bottom: 30px;">
      <div class="card-body" style="background-color: #<%= event.full? ? "A9A9A9" : hex_color_sample  %>;" align= "center">
        <%= link_to event.date, event %>
        <%= " [#{event.full_message}]" %><br>
        <%= "#{event.location}" %><br>
        <%= "#{event.max_player - event.confirms.count} slots left" %>
      </div>
    </div>
  </div>
  <% end %>
  </div>

app/views/users/edit.erb
<h1>Editing <%= @user.username %>'s account</h1>
<ul>
  <% if flash[:notice] %>
  <div class="alert alert-warning" role="alert">
    <% flash[:notice].each do |e| %>
        <li><%= e %></li>
    <% end %>
  <% end %>
</div>
</ul>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username, class: "form-control" %><br>
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %><br>
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %><br>
  <%= f.label :age %>
  <%= f.number_field :age, class: "form-control" %><br>
  <%= f.label "Profile Picture Link" %>
  <%= f.text_field :profile_img, class: "form-control" %><br>
  <%= f.submit "Update Account" %>
<% end %>

app/views/users/index.erb
<ul>
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
</ul>

<img src="https://i.ibb.co/sQ9ZmVS/Spash04.jpg" alt="Image" width = "100%" class=" shadow-lg rounded img-thumbnail">

<h3 align= "center">Upcoming Events</h3>
<div class="card-columns" style="column-gap: 30px;">
  <% @events.each do |event| %>
  <div class="card" style="margin-bottom: 30px;">
    <div class="card-body shadow-lg rounded" style="background-color: #<%= "#{hex_color_sample}" %>;" align= "center">
      <%= link_to image_tag(event.game.logo, width: "100%", class: "img-responsive center-block"), event %> <br>
      <%= "#{event.date}" %><br>
      <%= "#{event.location}" %><br>
      <%= "#{pluralize((event.max_player - event.confirms.count), "slot")} left" %>
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.erb
<h1 align= "center">Make a new LinkShell Account</h1>
<ul>
  <% if flash[:notice] %>
  <div class="alert alert-warning" role="alert">
    <%= flash[:notice]  %>
  <% end %>
</div>
</ul>
<%= form_for @user do |f| %>
  <div class="col-4 mx-auto">
  <%= f.label :username %>
  <%= f.text_field :username, class: "form-control"%><br>
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control", placeholder: "Emails are case sensitive and used for logging in"%><br>
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %><br>
  <%= f.label :age %>
  <%= f.number_field :age, class: "form-control" %><br>
  <%= f.label "Profile Picture Link" %>
  <%= f.text_field :profile_img, class: "form-control" %><br>
  </div>
  <%= f.submit "Make a new Account", class: "btn btn-primary btn-block col-2 mx-auto", form: "new_user" %>
<% end %>

app/views/users/show.erb
<h3><%= flash[:notice] %></h3>

<div class="col-4 float-left" align="center">
  <h1><%="#{@user.username}"%></h1>
  <img src="<%= @user.profile_img %>" alt="<%= @user.username %>" width = "300px" class= "img-thumbnail"><br><br>
  <% if session[:user_id] == @user.id %>
    <%= button_to "Update information", edit_user_path(@user), method: "get", class: "btn btn-primary border"%>
  <% end %>
</div>

<div class="accordion col-8 float-right" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne"
      <h2 class="m-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <h4>Game List</h4>
        </button>
      </h2>
    </div>
    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        <ul class="user-dropdown">
          <% @game_list.each do |game| %>
            <li><%= link_to game.name, game %></li>
          <% end %>
        </ul>
        <% if @game_list.count == 0 %>
          <p>You do not have any games added to your account.</p>
        <%end%>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header" id="headingTwo">
      <h2 class="m-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          <h4>Hosting</h4>
        </button>
      </h2>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
        <ul class="user-dropdown">
          <% @hostings.each do |host|%>
            <li><%= link_to "#{host.game.name}", host %> <br><%=  "#{host.date}" %></li>
          <% end %>
        </ul>
          <% if @hostings.count == 0 %>
            <p>You are not hosing any events.</p>
          <%end%>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header" id="headingThree">
      <h2 class="m-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          <h4>Attending</h4>
        </button>
      </h2>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
      <div class="card-body">
        <ul class="user-dropdown ">
          <% @events.map do |confirms|%>
            <li><%= link_to "#{confirms.event.game.name}", confirms.event %> <br> <%= "#{confirms.event.date}" %></li>
          <% end %>
        </ul>
        <% if @events.count == 0 %>
          <p>You are not currently attending any LinkShell events.</p>
        <%end%>
      </div>
    </div>
  </div>
</div>