config/routes.rb
Rails.application.routes.draw do
  post "users/logging", to: "users#login", as: "login_in"
  resources :events, except: [:destroy]
  resources :games, only: [:index, :show]
  resources :users, except: [:destroy]

  delete '/logout', to: 'sessions#destroy', as: "logout"
  root 'users#index'
  post "thereisnocowlevel", to: "events#destroy", as: "delete_event"
  post '/joinconfirms', to: "confirms#create", as: "join_event"
  post '.deleteconfirms', to: "confirms#destroy", as: "leave_event"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/confirm.rb
class Confirm < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :game
  belongs_to :user
  has_many :confirms, :dependent => :destroy
  has_many :users, through: :confirms

  validates :location, presence: true
  validates :date, presence: true
  validates :max_player, presence: true

  def full?
    self.users.count >= self.max_player
  end

  def full_message
    self.full? ? "Full" : "Open"
  end

  def self.index_events
    Event.all.select {|e| !e.full?}.shuffle[0..14].sort_by {|e| e.date}
  end

  def sorted_users
    self.users.sort_by {|u|u.username}
  end

  def self.open_events
    Event.all.select {|e| !e.full?}
  end

  def self.sort_by_date
    Event.all.sort_by {|e|e.date}
  end


end

app/models/game.rb
class Game < ApplicationRecord
  has_many :ownerships
  has_many :users, through: :ownerships
  has_many :events

  def self.sort_by_name
    Game.all.sort_by{ |game| game.name}
  end

  def game_name_platform
    "#{name} [#{platform}]"
  end

  def open_events
    events.all.select {|e| !e.full?}
  end

  def random_three_open_events
    open_events.sample(3).sort
  end

end

app/models/ownership.rb
class Ownership < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ownerships
  has_many :games, through: :ownerships
  has_many :events
  has_many :confirms

  validates :email, :username, uniqueness: true
  validates :email, :username,:profile_img, presence: true
  validates :email, :password, length: { minimum: 5 }
  validates :age, numericality: { greater_than_or_equal_to: 18 }

  def games_by_name
    self.games.sort_by{|g| g.name}
  end

  def self.random_user_id
    User.all.map {|u|u.id}.sample
  end


end

app/controllers/confirms_controller.rb
class ConfirmsController < ApplicationController

  def create
    Confirm.create(user_id: session[:user_id], event_id: session[:event_id])
    @event = Event.find(session[:event_id])
    session[:event_id] = nil
    redirect_to @event
  end

  def destroy
    Confirm.find_by(event_id: session[:event_id], user_id: session[:user_id]).destroy
    @event = Event.find(session[:event_id])
    session[:event_id] = nil
    redirect_to @event
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.sort_by_date
    @open_events = Event.open_events
  end

  def show
    @event = Event.find(params[:id])
    @confirms = @event.sorted_users
  end

  def new
    if session[:user_id].nil?
      redirect_to :root
    else
      @event = Event.new
      @games = Game.sort_by_name
    end
  end

  def create
    @event = Event.create(event_params)
    if @event.valid?
      Confirm.create(user_id: session[:user_id], event_id: @event.id)
      redirect_to @event
    else
      @games = Game.sort_by_name
      @errors = @event.errors.full_messages
      render :new
    end
  end

  def destroy
    Event.find(session[:event_id]).destroy
    session[:event_id] = nil
    @user = User.find(session[:user_id])
    @hostings = @user.events
    @game_list = @user.games_by_name
    @events = @user.confirms
    redirect_to @user
  end



  private
  def event_params
    params.require(:event).permit(:user_id, :game_id, :location, :max_player, :date)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.sort_by_name
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @events = Event.index_events
  end

  def login
    @user = User.find_by email: params[:email], password: params[:password]
    if @user.nil?
      @error = "Please check your Email and Password and Try again"
      redirect_to :root
    else
      session[:user_id] = @user.id
      redirect_to @user
    end
  end

  def show
    @user = User.find(params[:id])
    if @user.nil?
      redirect_to :root
    else
      @hostings = @user.events
      @game_list = @user.games_by_name
      @events = @user.confirms
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      flash[:notice] = "You account was sussessfully made."
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:notice] = @user.errors.full_messages
      redirect_to "/users/new"
    end
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == session[:user_id]
      redirect_to :root
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.valid?
      redirect_to @user
    else
      flash[:notice] = @user.errors.full_messages
      redirect_to "/users/#{params[:id]}/edit"
    end
  end



  private
  def user_params
    params.require(:user).permit(:email, :password, :age, :username, :profile_img)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirms_helper.rb
module ConfirmsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/ownerships_helper.rb
module OwnershipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinkShells</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- BOOTSTRAP CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/application.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <nav class="navbar navbar-fixed-top navbar-expand-lg navbar-dark border-dark" style="background-color: #7f6f9f" id="navbar" >
      <div class="collapse navbar-collapse " id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item ">
          <a class="nav-link" href="/">LinkShells<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/<%= User.random_user_id %>">Discover</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/games">Games</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/events">Events</a>
        </li>
          <% if session[:user_id].nil? %>
            <li class="nav-item">
              <a class="nav-link" href= <%= new_user_path %>>Sign Up</a>
            </li>
          <% else %>
          <li class="nav-item">
            <a class="nav-link" href= "/events/new"><%= "Host" if session[:user_id] %></a>
          </li>
          <% end %>
      </ul>
      </div>
    <div align="right" id="sign-in-form" >
      <% if session[:user_id].nil? && !current_page?("/users/new")%>
        <%= form_tag login_in_path do %>
        Email  <%= text_field_tag :email %>
        Password <%= password_field_tag :password %>
        <%= submit_tag "Login", class: "btn btn-primary"%>
        <% end %>
      <% end %>
    </div>
    <div class="float-right">
      <a class="navbar-brand" href="/users/<%= session[:user_id] %>"><%= User.find(session[:user_id]).username unless session[:user_id].nil?%></a>
    </div>
    <div class="float-right">
      <%= link_to "Sign out", logout_path, method: :delete, class: "nav-link  btn btn-secondary" if session[:user_id]%>
    </div>
  </nav>
  </header>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>